apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
        #  namespace: monitoring  
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: grafana
        image: grafana/grafana:latest
        securityContext:
          privileged: true
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
        - name: GF_USERS_DEFAULT_THEME
          value: "light"
        - name: GF_INSTALL_PLUGINS
          value: "yesoreyeram-infinity-datasource"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
            name: grafana-config
            readOnly: true
      volumes:
        - name: grafana-storage
          #emptyDir: {}
          persistentVolumeClaim:
            claimName: grafana-local-claim
        - name: grafana-config
          configMap:
              defaultMode: 420
              name: grafana-config
